const classKey = 'key';
const classButtonDisabled = 'button-disabled';

export const data = {
  letterBoard: {
    level1: {
      letterRow: ['asdf', 'asdf', 'asdf', 'asdf', 'asdf', 'asdf', 'asdf'],
      letterLines: 5,
    },
    level2: {
      letterRow: ['fdsa', 'fdsa', 'fdsa', 'fdsa', 'fdsa', 'fdsa', 'fdsa'],
      letterLines: 5,
    },
  },
  keyboard: [
    [
      { tecla: '\'', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '1', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '2', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '3', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '4', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '5', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '6', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '7', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '8', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '9', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '0', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '-', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '=', class: `${classKey} ${classButtonDisabled}` },
      { tecla: 'Backspace', class: `${classKey} ${classButtonDisabled} key-backspace` },
    ],
    [
      { tecla: 'Tab', class: `${classKey} ${classButtonDisabled}` },
      { tecla: 'q', class: `${classKey}` },
      { tecla: 'w', class: `${classKey}` },
      { tecla: 'e', class: `${classKey}` },
      { tecla: 'r', class: `${classKey}` },
      { tecla: 't', class: `${classKey}` },
      { tecla: 'y', class: `${classKey}` },
      { tecla: 'u', class: `${classKey}` },
      { tecla: 'i', class: `${classKey}` },
      { tecla: 'o', class: `${classKey}` },
      { tecla: 'p', class: `${classKey}` },
      { tecla: '´', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '[', class: `${classKey} ${classButtonDisabled}` },
      { tecla: 'Enter', class: `${classKey} ${classButtonDisabled} key-enter` },
    ],
    [
      { tecla: 'CapsLock', class: `${classKey} ${classButtonDisabled} key-capslock` },
      { tecla: 'a', class: `${classKey}` },
      { tecla: 's', class: `${classKey}` },
      { tecla: 'd', class: `${classKey}` },
      { tecla: 'f', class: `${classKey}` },
      { tecla: 'g', class: `${classKey}` },
      { tecla: 'h', class: `${classKey}` },
      { tecla: 'j', class: `${classKey}` },
      { tecla: 'k', class: `${classKey}` },
      { tecla: 'l', class: `${classKey}` },
      { tecla: 'ç', class: `${classKey}` },
      { tecla: '~', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '&#8262;', class: `${classKey} ${classButtonDisabled}` },
    ],
    [
      { tecla: 'Shift', class: `${classKey} key-l-shift` },
      { tecla: 'z', class: `${classKey}` },
      { tecla: 'x', class: `${classKey}` },
      { tecla: 'c', class: `${classKey}` },
      { tecla: 'v', class: `${classKey}` },
      { tecla: 'b', class: `${classKey}` },
      { tecla: 'n', class: `${classKey}` },
      { tecla: 'm', class: `${classKey}` },
      { tecla: ',', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '.', class: `${classKey} ${classButtonDisabled}` },
      { tecla: ';', class: `${classKey} ${classButtonDisabled}` },
      { tecla: '/', class: `${classKey} ${classButtonDisabled}` },
      { tecla: 'Shift', class: `${classKey} key-r-shift` },
    ],
    [
      { tecla: 'Control', class: `${classKey} ${classButtonDisabled} key-l-ctrl` },
      { tecla: 'Alt', class: `${classKey} ${classButtonDisabled} key-alt` },
      { tecla: 'space', class: `${classKey} key-space` },
      { tecla: 'AltGraph', class: `${classKey} ${classButtonDisabled} key-altgr` },
      { tecla: 'Control', class: `${classKey} ${classButtonDisabled} key-r-ctrl` },
    ],
  ],
};
